### ISSUE TITLE
Testing many versions of the same artifact

### ISSUE THREAD

**Issue by cobratbq** [s4u/pgp-keys-map#3]
I'm looking into verifying all `org.apache.maven.plugins` artifacts in one go. I'm working on a script to pull in everything, then download all the keys and do all the verification. It seems useful to have a reliable baseline for all the implicit plugins that maven uses. (I"ve done some work already and found some bad signatures along the way :-P)

But I'm a bit at a loss of how we're going to test all those jars. I was thinking, we do not have to perform the artifact validation through maven itself, because `pgpverify-maven-plugin` is the project that needs to work inside maven. But the `keys map` file may be tested in other ways.

@slawekjaranowski do you have any idea on how we could verify it if I provide you with an update to the `keys-map-list` that includes [fingerprints for all versions of all these artifacts](https://search.maven.org/search?q=g:org.apache.maven.plugins)?

**Comment by slawekjaranowski** [comment]
We can simply add section <plugin> without configuration and goals.
In this case listed plugin is not trigger but is included in verification.

I think that we can start with the latest version on plugins.
if we need many version for the same artifact/plugin we must put it in different module, like I test for junit many version.

**Comment by cobratbq** [comment]
> We can simply add section without configuration and goals. In this case listed plugin is not trigger but is included in verification.

Sure, that will work for one version of each.

>  if we need many version for the same artifact/plugin we must put it in different module, like I test for junit many version.

But we're not going to verify 30+ versions like that.

Okay, so let's go with latest version first and tackle the many-versions problem when we get to it.

**Comment by slawekjaranowski** [comment]
I will try to add org.apache.maven.plugins * with the latest version

**Comment by cobratbq** [comment]
We should also use [hard version specifiers](https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification), such as `[1.0]`, to ensure that maven's dependency resolution does not test for something other than was specified.
