### ISSUE TITLE
Prevent anything from running in 'install` and 'deploy` phases

### ISSUE THREAD

**Issue by cobratbq** [s4u/pgp-keys-map#6]
I'm considering to configure the (default) build plug-ins in `pgp-keys-map-test1` and `pgp-keys-map-test2` to not execute during `install`/`deploy` builds. To avoid these artifacts from showing up in local repositories. We would need to disable 3+ build plug-ins, so makes it a bit verbose.

What do you think?

**Comment by slawekjaranowski** [comment]
ok, only root must be install / deployed

**Comment by slawekjaranowski** [comment]
I will do it, I can test deploy
