### ISSUE TITLE
Verifying many artifact versions in same maven project

### ISSUE THREAD

**Issue by cobratbq** [s4u/pgp-keys-map#7]
Okay ... this one might be a bit nasty ... but I think we can (ab)use build plug-ins dependencies to list other versions of dependencies.

Maven seems to treat build plug-ins differently:
1. there is no version conflict resolution (hence version ranges are not valid)
1. I suspect plug-ins may be loaded in their own classloader (not confirmed yet)

I'm thinking, we only need a way to list multiple versions of dependencies. So, if we create/find a no-op build plug-in that does not rely on further dependencies, we add this build plug-in as many times as we need (with different ids), then add alternative versions of dependencies to it.

With https://github.com/s4u/pgpverify-maven-plugin/pull/56, we will simply read all dependencies and process their artifacts. The solution is not very elegant, but it could be very effective.

**Comment by slawekjaranowski** [comment]
s4u/pgpverify-maven-plugin#56 resolve this
